//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MineSharp.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string Account_SignIn {
            get {
                return ResourceManager.GetString("Account_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadly Microsoft has made it very hard to register an XBOX-OAuth Application. I have submitted the application for manual review though. For now, this is gonna stay cracked..
        /// </summary>
        internal static string Account_SignIn_TempCracked_Text {
            get {
                return ResourceManager.GetString("Account_SignIn_TempCracked_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft SignIn not possible.
        /// </summary>
        internal static string Account_SignIn_TempCracked_Title {
            get {
                return ResourceManager.GetString("Account_SignIn_TempCracked_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1234567890..
        /// </summary>
        internal static string AllowedCharacters_VersionString {
            get {
                return ResourceManager.GetString("AllowedCharacters_VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Instance.
        /// </summary>
        internal static string Instance_Create {
            get {
                return ResourceManager.GetString("Instance_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the Instance Name again..
        /// </summary>
        internal static string Instance_Create_Info_Name {
            get {
                return ResourceManager.GetString("Instance_Create_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a version using the provided identifier!.
        /// </summary>
        internal static string Instance_Create_Info_Version {
            get {
                return ResourceManager.GetString("Instance_Create_Info_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Loader . . ..
        /// </summary>
        internal static string Instance_Create_ModLoader {
            get {
                return ResourceManager.GetString("Instance_Create_ModLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Name . . ..
        /// </summary>
        internal static string Instance_Create_Name {
            get {
                return ResourceManager.GetString("Instance_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft Version . . ..
        /// </summary>
        internal static string Instance_Create_Version {
            get {
                return ResourceManager.GetString("Instance_Create_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Instance_Delete {
            get {
                return ResourceManager.GetString("Instance_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you continue, then the instance will get deleted forever! (A long time!).
        /// </summary>
        internal static string Instance_Delete_Continue_Text {
            get {
                return ResourceManager.GetString("Instance_Delete_Continue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string Instance_Delete_Continue_Title {
            get {
                return ResourceManager.GetString("Instance_Delete_Continue_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Instance_Edit {
            get {
                return ResourceManager.GetString("Instance_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Instance_Edit_General {
            get {
                return ResourceManager.GetString("Instance_Edit_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Instance_Edit_Height {
            get {
                return ResourceManager.GetString("Instance_Edit_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java and Memory.
        /// </summary>
        internal static string Instance_Edit_Java {
            get {
                return ResourceManager.GetString("Instance_Edit_Java", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory (MiB).
        /// </summary>
        internal static string Instance_Edit_Memory {
            get {
                return ResourceManager.GetString("Instance_Edit_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Name . . ..
        /// </summary>
        internal static string Instance_Edit_Name {
            get {
                return ResourceManager.GetString("Instance_Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Instance_Edit_Width {
            get {
                return ResourceManager.GetString("Instance_Edit_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string Instance_Edit_Window {
            get {
                return ResourceManager.GetString("Instance_Edit_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        internal static string Instance_OpenFolder {
            get {
                return ResourceManager.GetString("Instance_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Instance_Start {
            get {
                return ResourceManager.GetString("Instance_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m feeling lucky!.
        /// </summary>
        internal static string Instance_StartRandom {
            get {
                return ResourceManager.GetString("Instance_StartRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Instance_Stop {
            get {
                return ResourceManager.GetString("Instance_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfourtunately, this feature has not been implemented yet. Please wait for upcomming updates. I am probably working on this feature..
        /// </summary>
        internal static string Message_NotImplemented_Text {
            get {
                return ResourceManager.GetString("Message_NotImplemented_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Implemented.
        /// </summary>
        internal static string Message_NotImplemented_Title {
            get {
                return ResourceManager.GetString("Message_NotImplemented_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure, that you have executed the steps in the tutorial on GitHub. https://github.com/immortal640/MineSharp.
        /// </summary>
        internal static string MessageBox_Introduction_Text {
            get {
                return ResourceManager.GetString("MessageBox_Introduction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the Instructions.
        /// </summary>
        internal static string MessageBox_Introduction_Titile {
            get {
                return ResourceManager.GetString("MessageBox_Introduction_Titile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBSCRIBE TO KASAISORA!!!.
        /// </summary>
        internal static string TitleBar_Subscribe {
            get {
                return ResourceManager.GetString("TitleBar_Subscribe", resourceCulture);
            }
        }
    }
}
